from typing import Dict, Any

class WhatIfSimulator:
    def simulate(self, current_params: Dict[str, float], simulated_params: Dict[str, float]) -> Dict[str, Any]:
        curr_temp = current_params.get("temperature", 220.0)
        curr_press = current_params.get("pressure", 7.8)
        curr_rpm = current_params.get("rpm", 1450.0)
        curr_speed = current_params.get("speed", 70.0)
        curr_coolant = current_params.get("coolant_flow", 80.0)

        sim_temp = simulated_params.get("temperature", 210.0)
        sim_press = simulated_params.get("pressure", 7.3)
        sim_rpm = simulated_params.get("rpm", 1380.0)
        sim_speed = simulated_params.get("speed", 65.0)
        sim_coolant = simulated_params.get("coolant_flow", 95.0)

        # Physics-informed surrogate estimation
        # Delta calculations
        temp_delta = sim_temp - curr_temp
        press_delta = sim_press - curr_press
        rpm_delta = sim_rpm - curr_rpm
        speed_delta = sim_speed - curr_speed

        # Baseline Current Risk
        curr_defect_risk = 0.78
        if curr_temp < 215 and curr_press < 7.5 and curr_rpm < 1400:
            curr_defect_risk = 0.18
        elif curr_temp > 240 or curr_rpm > 1650:
            curr_defect_risk = 0.82

        # Simulated Impact
        # Lower temperature & optimal pressure & moderate RPM reduces defect probability
        temp_factor = (sim_temp - 200.0) / 40.0 # optimal around 200°C
        press_factor = abs(sim_press - 7.2) / 2.0 # optimal around 7.2 bar
        rpm_factor = (sim_rpm - 1350.0) / 300.0 # optimal around 1350 RPM

        sim_defect_prob = max(0.04, min(0.95, 0.15 + (temp_factor * 0.25) + (press_factor * 0.20) + (rpm_factor * 0.20)))
        sim_defect_prob = round(sim_defect_prob, 2)

        curr_quality = max(55.0, round(100.0 - (curr_defect_risk * 50.0), 1))
        sim_quality = min(99.0, max(60.0, round(100.0 - (sim_defect_prob * 45.0), 1)))

        curr_scrap = round(curr_defect_risk * 23.0, 1)
        sim_scrap = round(sim_defect_prob * 18.0, 1)

        # Production time impact based on RPM and speed change
        rpm_ratio = curr_rpm / max(100.0, sim_rpm)
        time_change_pct = round((rpm_ratio - 1.0) * 100.0 * 0.45, 1)
        time_sign = "+" if time_change_pct >= 0 else ""

        # Energy consumption delta
        energy_saving = round(abs(temp_delta * 0.15) + (rpm_delta < 0) * 4.2, 1)

        return {
            "is_model_estimate": True,
            "disclaimer": "Simulated estimates generated by physics-informed surrogate model for decision-support testing.",
            "current_state": {
                "temperature": curr_temp,
                "pressure": curr_press,
                "rpm": curr_rpm,
                "speed": curr_speed,
                "coolant_flow": curr_coolant,
                "defect_probability": round(curr_defect_risk * 100, 1),
                "quality_score": curr_quality,
                "estimated_scrap_rate": curr_scrap,
                "thermal_stability": "UNSTABLE" if curr_temp > 235 else "STABLE"
            },
            "simulated_state": {
                "temperature": sim_temp,
                "pressure": sim_press,
                "rpm": sim_rpm,
                "speed": sim_speed,
                "coolant_flow": sim_coolant,
                "defect_probability": round(sim_defect_prob * 100, 1),
                "quality_score": sim_quality,
                "estimated_scrap_rate": sim_scrap,
                "production_time_delta": f"{time_sign}{time_change_pct}%",
                "energy_saving_delta": f"+{energy_saving}%",
                "thermal_stability": "OPTIMAL" if sim_temp <= 215 else "MARGINAL"
            },
            "impact_deltas": {
                "defect_prob_reduction": f"{round(curr_defect_risk * 100, 1)}% → {round(sim_defect_prob * 100, 1)}%",
                "quality_score_improvement": f"{curr_quality} → {sim_quality}",
                "scrap_reduction": f"{curr_scrap}% → {sim_scrap}%",
                "production_time": f"{time_sign}{time_change_pct}%"
            },
            "recommendation_summary": f"Adjusting Spindle RPM from {curr_rpm} to {sim_rpm} and target temperature to {sim_temp}°C yields an estimated {round((curr_quality - sim_quality) * -1, 1)} pt quality score recovery with {sim_scrap}% projected scrap."
        }

what_if_simulator = WhatIfSimulator()
