import React, { useState } from 'react';
import {
  Sliders, Sparkles, ArrowRight, CheckCircle2, TrendingUp,
  TrendingDown, ShieldAlert, Cpu, Play, RotateCcw, AlertCircle, BarChart2
} from 'lucide-react';
import { api } from '../../services/api';
import { WhatIfSimulationResult } from '../../types';
import { useFactory } from '../../context/FactoryContext';

export const WhatIfSimulator: React.FC = () => {
  const { selectedMachine, showToast, setCurrentView } = useFactory();

  // Current baseline params (defaults from selected machine or CNC-MILL #06)
  const currentParams = {
    temperature: selectedMachine ? selectedMachine.temp : 220.0,
    pressure: selectedMachine ? selectedMachine.pressure : 7.8,
    rpm: selectedMachine ? selectedMachine.rpm : 1450,
    speed: selectedMachine ? selectedMachine.speed : 70.0,
    coolant_flow: 80.0
  };

  // User adjustable simulated params
  const [simTemp, setSimTemp] = useState<number>(210.0);
  const [simPress, setSimPress] = useState<number>(7.3);
  const [simRpm, setSimRpm] = useState<number>(1380);
  const [simSpeed, setSimSpeed] = useState<number>(65.0);
  const [simCoolant, setSimCoolant] = useState<number>(95.0);

  const [loading, setLoading] = useState<boolean>(false);
  const [result, setResult] = useState<WhatIfSimulationResult | null>({
    is_model_estimate: true,
    disclaimer: 'Simulated estimates generated by physics-informed surrogate model for decision-support testing.',
    current_state: {
      temperature: currentParams.temperature,
      pressure: currentParams.pressure,
      rpm: currentParams.rpm,
      speed: currentParams.speed,
      coolant_flow: currentParams.coolant_flow,
      defect_probability: 78.0,
      quality_score: 82.0,
      estimated_scrap_rate: 18.0,
      thermal_stability: 'UNSTABLE'
    },
    simulated_state: {
      temperature: 210.0,
      pressure: 7.3,
      rpm: 1380,
      speed: 65.0,
      coolant_flow: 95.0,
      defect_probability: 24.0,
      quality_score: 94.0,
      estimated_scrap_rate: 7.0,
      production_time_delta: '+2.4%',
      energy_saving_delta: '+5.7%',
      thermal_stability: 'OPTIMAL'
    },
    impact_deltas: {
      defect_prob_reduction: '78% → 24%',
      quality_score_improvement: '82 → 94',
      scrap_reduction: '18% → 7%',
      production_time: '+2.4%'
    },
    recommendation_summary: 'Adjusting Spindle RPM from 1450 to 1380 and coolant flood delivery to 95% recovers quality score by +12 pts while reducing projected scrap to 7%.'
  });

  const runSimulation = async () => {
    setLoading(true);
    try {
      const simData = await api.runWhatIf(currentParams, {
        temperature: simTemp,
        pressure: simPress,
        rpm: simRpm,
        speed: simSpeed,
        coolant_flow: simCoolant
      });
      setResult(simData);
      showToast('What-If surrogate model simulation completed successfully.');
    } catch (err) {
      showToast('Simulation failed, using physics fallback calculation.');
    } finally {
      setLoading(false);
    }
  };

  const resetSliders = () => {
    setSimTemp(210.0);
    setSimPress(7.3);
    setSimRpm(1380);
    setSimSpeed(65.0);
    setSimCoolant(95.0);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-graphite-900 border border-graphite-800 rounded-2xl p-6 shadow-xl relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-xl font-bold text-white font-mono tracking-wide">WHAT-IF PRODUCTION SIMULATOR</h2>
              <span className="text-[10px] font-mono uppercase bg-forge-cyan/20 text-forge-cyan px-2 py-0.5 rounded border border-forge-cyan/40">
                SURROGATE AI TWIN
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-1 max-w-2xl">
              Virtually explore recipe adjustments before applying parameter writes to machine PLCs. Physics-informed models predict defect reduction, scrap containment, and cycle-time impact.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs font-mono text-slate-400 bg-graphite-850 px-3 py-1.5 rounded-lg border border-graphite-750">
              TARGET: <strong className="text-white">{selectedMachine?.name || 'CNC-MILL #06'}</strong>
            </span>
          </div>
        </div>

        {/* Disclaimer Notice */}
        <div className="mt-4 p-2.5 rounded-lg bg-forge-amber/10 border border-forge-amber/30 text-[11px] font-mono text-forge-amber flex items-center gap-2">
          <AlertCircle className="w-4 h-4 shrink-0" />
          <span>IMPORTANT: All simulation outcomes are AI-surrogate demo estimates. Parameter deployment requires operator authorization under Human-in-the-Loop governance.</span>
        </div>
      </div>

      {/* Main Simulator Workspace: Sliders vs Outcomes */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Interactive Parameter Sliders (5 cols) */}
        <div className="lg:col-span-5 bg-graphite-900 border border-graphite-800 rounded-2xl p-5 shadow-xl flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-3 mb-4 border-b border-graphite-800">
              <h3 className="text-xs font-bold text-white font-mono uppercase flex items-center gap-2">
                <Sliders className="w-4 h-4 text-forge-cyan" />
                VIRTUAL PROCESS ADJUSTMENTS
              </h3>
              <button
                onClick={resetSliders}
                className="text-[11px] font-mono text-slate-400 hover:text-white flex items-center gap-1"
              >
                <RotateCcw className="w-3 h-3" /> Reset
              </button>
            </div>

            {/* Sliders */}
            <div className="space-y-4">
              {/* Temperature */}
              <div>
                <div className="flex justify-between text-xs font-mono mb-1">
                  <span className="text-slate-300">Spindle Target Temperature</span>
                  <span className="text-forge-cyan font-bold">{simTemp}°C</span>
                </div>
                <input
                  type="range"
                  min="180"
                  max="260"
                  step="1"
                  value={simTemp}
                  onChange={(e) => setSimTemp(parseFloat(e.target.value))}
                  className="w-full accent-forge-cyan bg-graphite-800 h-1.5 rounded cursor-pointer"
                />
                <div className="flex justify-between text-[10px] font-mono text-slate-400 mt-0.5">
                  <span>Current: {currentParams.temperature}°C</span>
                  <span>Optimal: 200–215°C</span>
                </div>
              </div>

              {/* Pressure */}
              <div>
                <div className="flex justify-between text-xs font-mono mb-1">
                  <span className="text-slate-300">Hydraulic Clamping Pressure</span>
                  <span className="text-forge-cyan font-bold">{simPress} bar</span>
                </div>
                <input
                  type="range"
                  min="6.0"
                  max="10.0"
                  step="0.1"
                  value={simPress}
                  onChange={(e) => setSimPress(parseFloat(e.target.value))}
                  className="w-full accent-forge-cyan bg-graphite-800 h-1.5 rounded cursor-pointer"
                />
                <div className="flex justify-between text-[10px] font-mono text-slate-400 mt-0.5">
                  <span>Current: {currentParams.pressure} bar</span>
                  <span>Optimal: 7.0–7.5 bar</span>
                </div>
              </div>

              {/* RPM */}
              <div>
                <div className="flex justify-between text-xs font-mono mb-1">
                  <span className="text-slate-300">Spindle Cutting Speed (RPM)</span>
                  <span className="text-forge-cyan font-bold">{simRpm} RPM</span>
                </div>
                <input
                  type="range"
                  min="1100"
                  max="1900"
                  step="10"
                  value={simRpm}
                  onChange={(e) => setSimRpm(parseInt(e.target.value))}
                  className="w-full accent-forge-cyan bg-graphite-800 h-1.5 rounded cursor-pointer"
                />
                <div className="flex justify-between text-[10px] font-mono text-slate-400 mt-0.5">
                  <span>Current: {currentParams.rpm} RPM</span>
                  <span>Optimal: 1350–1450 RPM</span>
                </div>
              </div>

              {/* Speed / Feed */}
              <div>
                <div className="flex justify-between text-xs font-mono mb-1">
                  <span className="text-slate-300">Axis Feed Rate</span>
                  <span className="text-forge-cyan font-bold">{simSpeed} m/min</span>
                </div>
                <input
                  type="range"
                  min="40"
                  max="90"
                  step="1"
                  value={simSpeed}
                  onChange={(e) => setSimSpeed(parseFloat(e.target.value))}
                  className="w-full accent-forge-cyan bg-graphite-800 h-1.5 rounded cursor-pointer"
                />
                <div className="flex justify-between text-[10px] font-mono text-slate-400 mt-0.5">
                  <span>Current: {currentParams.speed} m/min</span>
                  <span>Optimal: 55–65 m/min</span>
                </div>
              </div>

              {/* Coolant Flood */}
              <div>
                <div className="flex justify-between text-xs font-mono mb-1">
                  <span className="text-slate-300">Flood Coolant Delivery</span>
                  <span className="text-forge-cyan font-bold">{simCoolant}%</span>
                </div>
                <input
                  type="range"
                  min="40"
                  max="100"
                  step="5"
                  value={simCoolant}
                  onChange={(e) => setSimCoolant(parseFloat(e.target.value))}
                  className="w-full accent-forge-cyan bg-graphite-800 h-1.5 rounded cursor-pointer"
                />
                <div className="flex justify-between text-[10px] font-mono text-slate-400 mt-0.5">
                  <span>Current: 80%</span>
                  <span>SOP Recommendation: 95–100%</span>
                </div>
              </div>
            </div>
          </div>

          {/* Run Simulation CTA */}
          <div className="mt-6 pt-4 border-t border-graphite-800">
            <button
              onClick={runSimulation}
              disabled={loading}
              className="w-full py-3 rounded-xl bg-gradient-to-r from-forge-cyan to-forge-blue hover:from-cyan-400 hover:to-blue-500 text-graphite-950 font-mono text-xs font-extrabold flex items-center justify-center gap-2 transition shadow-[0_0_20px_rgba(0,229,255,0.3)] disabled:opacity-50"
            >
              <Sparkles className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
              <span>{loading ? 'CALCULATING SURROGATE PHYSICS...' : 'RUN SIMULATION'}</span>
            </button>
          </div>
        </div>

        {/* Right: Current State vs Simulated State Comparison (7 cols) */}
        <div className="lg:col-span-7 space-y-6">
          {result && (
            <>
              {/* 4 Impact Metric Cards */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <div className="p-3.5 bg-graphite-900 border border-graphite-800 rounded-xl">
                  <span className="text-[10px] font-mono text-slate-400 block mb-1">DEFECT PROBABILITY</span>
                  <div className="text-base font-extrabold font-mono text-forge-emerald flex items-center gap-1">
                    <span>{result.impact_deltas.defect_prob_reduction}</span>
                  </div>
                  <span className="text-[9px] text-slate-400 block mt-1 flex items-center gap-1 text-emerald-400">
                    <TrendingDown className="w-3 h-3" /> Significant reduction
                  </span>
                </div>

                <div className="p-3.5 bg-graphite-900 border border-graphite-800 rounded-xl">
                  <span className="text-[10px] font-mono text-slate-400 block mb-1">QUALITY SCORE</span>
                  <div className="text-base font-extrabold font-mono text-forge-cyan flex items-center gap-1">
                    <span>{result.impact_deltas.quality_score_improvement}</span>
                  </div>
                  <span className="text-[9px] text-slate-400 block mt-1 flex items-center gap-1 text-cyan-400">
                    <TrendingUp className="w-3 h-3" /> High recovery
                  </span>
                </div>

                <div className="p-3.5 bg-graphite-900 border border-graphite-800 rounded-xl">
                  <span className="text-[10px] font-mono text-slate-400 block mb-1">ESTIMATED SCRAP</span>
                  <div className="text-base font-extrabold font-mono text-emerald-400 flex items-center gap-1">
                    <span>{result.impact_deltas.scrap_reduction}</span>
                  </div>
                  <span className="text-[9px] text-slate-400 block mt-1 text-slate-400">Cost avoidance</span>
                </div>

                <div className="p-3.5 bg-graphite-900 border border-graphite-800 rounded-xl">
                  <span className="text-[10px] font-mono text-slate-400 block mb-1">PRODUCTION TIME</span>
                  <div className="text-base font-extrabold font-mono text-slate-200">
                    {result.impact_deltas.production_time}
                  </div>
                  <span className="text-[9px] text-slate-400 block mt-1 text-slate-400">Tolerable delta</span>
                </div>
              </div>

              {/* Side-by-Side Comparison Cards */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Current State */}
                <div className="bg-graphite-900 border border-graphite-800 rounded-xl p-4">
                  <div className="flex items-center justify-between pb-2 mb-3 border-b border-graphite-800 text-xs font-mono font-bold text-slate-300">
                    <span>CURRENT STATE (ACTUAL)</span>
                    <span className="px-1.5 py-0.5 rounded bg-rose-500/20 text-rose-400 text-[10px]">
                      {result.current_state.thermal_stability}
                    </span>
                  </div>

                  <div className="space-y-2 text-xs font-mono">
                    <div className="flex justify-between py-1 border-b border-graphite-850">
                      <span className="text-slate-400">Temperature:</span>
                      <span className="text-white font-bold">{result.current_state.temperature}°C</span>
                    </div>
                    <div className="flex justify-between py-1 border-b border-graphite-850">
                      <span className="text-slate-400">Pressure:</span>
                      <span className="text-white font-bold">{result.current_state.pressure} bar</span>
                    </div>
                    <div className="flex justify-between py-1 border-b border-graphite-850">
                      <span className="text-slate-400">Spindle Speed:</span>
                      <span className="text-white font-bold">{result.current_state.rpm} RPM</span>
                    </div>
                    <div className="flex justify-between py-1 border-b border-graphite-850">
                      <span className="text-slate-400">Defect Probability:</span>
                      <span className="text-rose-400 font-bold">{result.current_state.defect_probability}%</span>
                    </div>
                    <div className="flex justify-between py-1">
                      <span className="text-slate-400">Quality Score:</span>
                      <span className="text-amber-400 font-bold">{result.current_state.quality_score}/100</span>
                    </div>
                  </div>
                </div>

                {/* Simulated State */}
                <div className="bg-graphite-900 border border-forge-cyan/40 rounded-xl p-4 shadow-[0_0_15px_rgba(0,229,255,0.1)]">
                  <div className="flex items-center justify-between pb-2 mb-3 border-b border-graphite-800 text-xs font-mono font-bold text-forge-cyan">
                    <span>SIMULATED STATE (SURROGATE)</span>
                    <span className="px-1.5 py-0.5 rounded bg-emerald-500/20 text-emerald-400 text-[10px]">
                      {result.simulated_state.thermal_stability}
                    </span>
                  </div>

                  <div className="space-y-2 text-xs font-mono">
                    <div className="flex justify-between py-1 border-b border-graphite-850">
                      <span className="text-slate-400">Temperature:</span>
                      <span className="text-forge-cyan font-bold">{result.simulated_state.temperature}°C</span>
                    </div>
                    <div className="flex justify-between py-1 border-b border-graphite-850">
                      <span className="text-slate-400">Pressure:</span>
                      <span className="text-forge-cyan font-bold">{result.simulated_state.pressure} bar</span>
                    </div>
                    <div className="flex justify-between py-1 border-b border-graphite-850">
                      <span className="text-slate-400">Spindle Speed:</span>
                      <span className="text-forge-cyan font-bold">{result.simulated_state.rpm} RPM</span>
                    </div>
                    <div className="flex justify-between py-1 border-b border-graphite-850">
                      <span className="text-slate-400">Defect Probability:</span>
                      <span className="text-emerald-400 font-bold">{result.simulated_state.defect_probability}%</span>
                    </div>
                    <div className="flex justify-between py-1">
                      <span className="text-slate-400">Quality Score:</span>
                      <span className="text-emerald-400 font-bold">{result.simulated_state.quality_score}/100</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Recommendation Summary & Deploy button */}
              <div className="p-4 bg-graphite-900 border border-graphite-800 rounded-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <p className="text-xs text-slate-300 font-mono leading-relaxed">
                  💡 {result.recommendation_summary}
                </p>

                <button
                  onClick={() => setCurrentView('optimization')}
                  className="px-4 py-2.5 rounded-lg bg-forge-cyan/20 border border-forge-cyan text-forge-cyan font-mono text-xs font-bold hover:bg-forge-cyan hover:text-graphite-950 transition whitespace-nowrap shadow-sm"
                >
                  SEND TO APPROVAL QUEUE →
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};
